name: Check Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run lint
    - run: npm test
      env:
        FRONTEND_URL: https://stage-frontend-reactjs.herokuapp.com, https://stage-frontend-angular.herokuapp.com
        MONGO_DB_URI: mongodb+srv://root:root@cluster0.o9bjq.mongodb.net/tellefy?retryWrites=true&w=majority
        TEST_LOCAL_SERVER_PORT: 3000
        TEST_LOCAL_SERVER: true